# The Data Portal and EHR Integration Working Group {#dpehri}

## Mandate {#dpehri_mandate}

The EHR integration and Data Portal WG will be the forum for design and implementation of data models, workflows, and interrelated platforms for integrating the diverse datasets and data resources applicable to HeartShare.

Working closely with informatics and data science professionals across the consortium, the EHRI and DP WG will ensure that the processes for acquiring and integrating data -- including extant cohorts, EHR, and imaging data -- are sound, secure, effective, and adherent with the research protocols of HeartShare.

## EHR Integration Purpose {#dpehri_aim}

The goal is to functionally integrate clinical care data for HF patients and their comparator group from the HeartShare Clinical Centers (CCs). These data sets are not intended for discovery of novel HFpEF phenotypes. Rather they will be used to:

-   Describe and characterize the scope, composition and ready availability of EHR data for HF patients across HeartShare
-   Aid the identification and enrollment of HF and HFpEF patients with bespoke clinical features into the HeartShare Study if and when needed
-   Provide a platform for the real-world application of EHR-based HFpEF phenotypes which can be used to find patient sub-populations and drive iterative phenotype validation and refinement.
-   Resource for investigators interested in multi-site analyses e.g. study the uptake of specific treatments, gather pilot data to support ancillary grants, or trainees working on their projects
