# HeartShare Retrospective Cohort Details 

## Cohort

As currently proposed, there will be **two cohorts** of HF patients whose records are to be included in the OMOP tables. This does not include their comparator groups yet as the cohort definition criteria for them is still being developed.

### Historical HF Patients at CC

#### Selection criteria

Selection criteria: follow DTC guidelines to identify HF patients (all EFs) in the EHR 2016 onwards (ICD-10 implementation date), namely:

-   Age: $\geq$ 18, if used age cut off at 30 as had been previously discussed just indicate that
-   Presence of ICD-10 Codes: 2 outpatient encounters or 1 inpatient (for list of codes see below)

Please do not use any additional filtering criteria. If you are using any (e.g., BNP cut off value) please indicate that in your response to the DTC.

#### ICD-10 Codes

```
I09.81,  I11.0,  I13.0,  I13.2,  I50.1,  
I50.20,  I50.21,  I50.22,  I50.23,  I50.30,  
I50.31,  I50.32,  I50.33,  I50.40,  I50.41,  
I50.42,  I50.43,  I50.810,  I50.811,  I50.812,  
I50.813,  I50.814,  I50.82,  I50.83,  I50.84,  
I50.89,  I50.9
```

### HF Patients Prospectively Enrolled in the HeartShare Study

Patients in the HF arms of the HeartShare Study, both the HeartShare HF Registry and the HFpEF Deep Phenotyping Cohorts, are also to be included as they enroll in the study and provide informed consent and EHR authorization via the Eureka app.

## OMOP Tables Usage

```{r, colorize, echo=FALSE}
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

All the tables are congruent with [**OMOP CDM v.5.3.1**](https://ohdsi.github.io/CommonDataModel/cdm53.html). Required tables are expected to be populated with the data and are listed in **`r colorize("bold letters", "black")`**. Optional tables can be left empty for now are listed in `r colorize("gray", "gray")`. A link to the corresponding table definitions in the OMOP CDM is provided for each table.

If possible, we ask that patient data for the tables are populated starting 10 years prior to the date patient qualified for the cohort (selection criteria looks in the EHR records starting with year 2016; If patient qualified in 2020, cohort should include patients' data from 2010 onwards).

We anticipate managing HeartShare cohorts by using OMOP CDM COHORT% tables. More information will follow.

### Clinical Data Tables

[https://ohdsi.github.io/CommonDataModel/cdm53.html#Clinical_Data_Tables](https://ohdsi.github.io/CommonDataModel/cdm53.html#Clinical_Data_Tables)

-   [**`r colorize("PERSON","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#PERSON)

-   [**`r colorize("OBSERVATION\\_PERIOD","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#OBSERVATION_PERIOD)

-   [**`r colorize("VISIT\\_OCCURENCE","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#VISIT_OCCURRENCE)

-   [`r colorize("VISIT\\_DETAIL","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#VISIT_DETAIL)

-   [**`r colorize("CONDITION\\_OCCURRENCE","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONDITION_OCCURRENCE)

-   [**`r colorize("DRUG\\_EXPOSURE","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#DRUG_EXPOSURE)

    - If possible, we recommend loading all of the medication data. For sites	that are building de novo OMOP tables, selective loading should focus on cardiovascular drugs that fall under the following ATC classes: alimentary tract and metabolism, blood and blood forming organs, and cardiovascular systems.

-   [**`r colorize("PROCEDURE\\_OCCURRENCE","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#PROCEDURE_OCCURRENCE)

    - If possible, we recommend loading all procedures. In particular, we would like sites to confirm the loading  of [these procedures](https://athena.ohdsi.org/search-terms/terms/45888880).

-   [`r colorize("DEVICE\\_EXPOSURE","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#DEVICE_EXPOSURE)

-   [**`r colorize("MEASUREMENT","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#MEASUREMENT)

    - If possible, we recommend loading all of measurement data, including vitals. For sites that are building de novo OMOP tables, lists of high value labs and vitals will be forthcoming for selective loading.

    - See details for loading echocardiogram data below.

-   [**`r colorize("OBSERVATION","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#OBSERVATION)

-   [**`r colorize("DEATH","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#DEATH)

-   [**`r colorize("NOTE","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#NOTE)

    - We recommend loading notes for echocardiogram, cardiac cath, and ECG if possible. Our initial priority will be loading echo notes locally. At Northwestern, we have used both an internally-developed text de-identification tool as well as an open source tool from Stanford called [TiDE](https://starr.stanford.edu/methods/tide-text-deid).

-   [`r colorize("NOTE\\_NLP","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#NOTE_NLP)

-   [`r colorize("SPECIMEN","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#SPECIMEN)

-   [`r colorize("FACT\\_RELATIONSHIP", "gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#FACT_RELATIONSHIP)

### Health System Data Tables

[https://ohdsi.github.io/CommonDataModel/cdm53.html#Health_System_Data_Tables](https://ohdsi.github.io/CommonDataModel/cdm53.html#Health_System_Data_Tables) 

-   [`r colorize("LOCATION","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#Health_System_Data_Tables)

-   [`r colorize("CARE\\_SITE","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#CARE_SITE)

-   [`r colorize("PROVIDER","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#PROVIDER)

### Health Economics Data Tables

[https://ohdsi.github.io/CommonDataModel/cdm53.html#Health_Economics_Data_Tables](https://ohdsi.github.io/CommonDataModel/cdm53.html#Health_Economics_Data_Tables) 

-   [`r colorize("PAYER\\_PLAN\\_PERIOD","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#PAYER_PLAN_PERIOD)

-   [`r colorize("COST","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#COST)

### Standardized Derived Elements

[https://ohdsi.github.io/CommonDataModel/cdm53.html#Standardized_Derived_Elements](https://ohdsi.github.io/CommonDataModel/cdm53.html#Standardized_Derived_Elements) 

-   [**`r colorize("DRUG\\_ERA","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#DRUG_ERA)

-   [`r colorize("DOSE\\_ERA","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#DOSE_ERA)

-   [**`r colorize("CONDITION\\_ERA","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONDITION_ERA)

### Vocabulary Tables

[https://ohdsi.github.io/CommonDataModel/cdm53.html#Vocabulary_Tables](https://ohdsi.github.io/CommonDataModel/cdm53.html#Vocabulary_Tables) 

-   [**`r colorize("CONCEPT","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONCEPT)

-   [**`r colorize("VOCABULARY","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#VOCABULARY)

-   [**`r colorize("DOMAIN","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#DOMAIN)

-   [**`r colorize("CONCEPT\\_CLASS","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONCEPT_CLASS)

-   [**`r colorize("CONCEPT\\_RELATIONSHIP", "black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONCEPT_RELATIONSHIP)

-   [**`r colorize("RELATIONSHIP","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#RELATIONSHIP)

-   [**`r colorize("CONCEPT\\_SYNONYM","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONCEPT_SYNONYM)

-   [**`r colorize("CONCEPT\\_ANCESTOR","black")`**](https://ohdsi.github.io/CommonDataModel/cdm53.html#CONCEPT_ANCESTOR)

-   [`r colorize("SOURCE\\_TO\\_CONCEPT\\_MAP","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#SOURCE_TO_CONCEPT_MAP)

-   [`r colorize("DRUG\\_STRENGTH","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#DRUG_STRENGTH)

-   [`r colorize("COHORT\\_DEFINITION","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#COHORT_DEFINITION)

-   [`r colorize("ATTRIBUTE\\_DEFINITION","gray")`](https://ohdsi.github.io/CommonDataModel/cdm53.html#ATTRIBUTE_DEFINITION)


### Vocabularies to Load

Vocabularies can be downloaded from [https://athena.ohdsi.org/vocabulary/list](https://athena.ohdsi.org/vocabulary/list).
Size of OMOP vocabularies is typically in the range of ~20GB. At a minimum, it is recommended to use the vocabularies below:

ID (CDM V4.5)|CODE (CDM V5)|NAME|LATEST UPDATE
---|---|---|---
1|SNOMED|Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)|27-Jan-22
2|ICD9CM|International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)|30-Sep-14
3|ICD9Proc|International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 3 (NCHS)|30-Sep-14
4|CPT4|Current Procedural Terminology version 4 (AMA)|30-Apr-23
5|HCPCS|Healthcare Common Procedure Coding System (CMS)|30-Jun-23
6|LOINC|Logical Observation Identifiers Names and Codes (Regenstrief Institute)|14-Aug-23
8|RxNorm|RxNorm (NLM)|2-Jul-23
9|NDC|National Drug Code (FDA and manufacturers)|26-Aug-23
12|Gender|OMOP Gender|0-Jan-00
13|Race|Race and Ethnicity Code Set (USBC)|0-Jan-00
14|CMS Place of Service|Place of Service Codes for Professional Claims (CMS)|0-Jan-00
21|ATC|WHO Anatomic Therapeutic Chemical Classification|6-Sep-21
35|ICD10PCS|ICD-10 Procedure Coding System (CMS)|30-Sep-20
40|DRG|Diagnosis-related group (CMS)|0-Jan-00
41|MDC|Major Diagnostic Categories (CMS)|0-Jan-00
44|Ethnicity|OMOP Ethnicity|0-Jan-00
70|ICD10CM|International Classification of Diseases, Tenth Revision, Clinical Modification (NCHS)|30-Sep-22
82|RxNorm Extension|OMOP RxNorm Extension|23-Aug-23
88|CVX|CDC Vaccine Administered CVX (NCIRD)|17-Apr-23
115|Provider|OMOP Provider|0-Jan-00
128|OMOP Extension|OMOP Extension (OHDSI)|30-May-23

### Echo Measurement

Echo measurements should be loaded into the MEASUREMENT table. Most of the echo variables could be matched to appropriate LOINC code(s). For variables where suitable standard codes were not found, custom vocabulary and custom concept mappings were created for capturing those values.The echo measurements should be able to be linked to echos in the PROCEDURE_OCCURRENCE table. For left ventricular ejection fraction, we recommend mapping the value in the echo reported by the echocardiographer to the most appropriate LOINC code. If the method of measurement is unknown, then use LOINC Code 8806-2, Left ventricular Ejection fraction by 2D echo.

[Echo Variables Mappings](https://heartsharestudy.github.io/PHENOTYPES/Echo Variables Mapping.html)

[Echo Variables Custom Vocabulary](https://heartsharestudy.github.io/PHENOTYPES/HeartShare Vocabulary.html)


